HTMXListViewDemo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hr_app.urls')),
]

hr_app/urls.py
from django.urls import path

from . import views

app_name = "hr"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('list/', views.PersonListView.as_view(), name='person_list'),
]

hr_app/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=255)
    date_of_birth = models.DateField()
    email = models.EmailField()
    street_address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)

    @property
    def age(self):
        return timezone.now().year - self.date_of_birth.year

HTMXListViewDemo/views.py
from urllib.parse import urlencode

from django.core.exceptions import FieldError
from django.views.generic import ListView

from .utils import build_filter_dict, build_query_str, build_filters_template_dict


class HtmxListView(ListView):
    target_id = ""

    def setup(self, request, *args, **kwargs):
        super(HtmxListView, self).setup(request, *args, **kwargs)
        self.filter = build_filter_dict(request.GET)
        self.query = build_query_str(request.GET)
        self.filter_query = self.query

        if "order_by" in request.GET:
            self.order_by = request.GET.get('order_by')

        if not self.order_by:
            self.order_by = "pk"

        self.query += f"&order_by={self.order_by}"

    def get_queryset(self):
        qs = super(HtmxListView, self).get_queryset()
        if hasattr(self, 'filter') and self.filter:
            qs = qs.filter(**self.filter)
        if hasattr(self, 'order_by') and self.order_by:
            try:
                qs = qs.order_by(self.order_by)
            except FieldError:
                # Most likely a @property, try to sort a different way
                # Experimental, sometimes works, sometimes not
                sort_key = self.order_by
                reversed = False
                if sort_key.startswith('-'):
                    reversed = True
                    sort_key = sort_key[1:]

                qs = sorted(qs.order_by("pk"), key=lambda obj: getattr(obj, sort_key, None), reverse=reversed)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query_params = {p: v for p, v in self.request.GET.items() if p != 'page'}
        context["query_params"] = urlencode(query_params, doseq=True)

        if hasattr(self, 'paginate_by') and self.paginate_by:
            if not hasattr(self, 'elided_each_side'):
                self.elided_each_side = 1

            if not hasattr(self, 'elided_ends'):
                self.elided_ends = 1

            context["page_range"] = context["paginator"].get_elided_page_range(
                number=context["page_obj"].number, on_each_side=self.elided_each_side, on_ends=self.elided_ends
            )
            context["paginator"].allow_empty_first_page = True

        context["order_by"] = self.order_by
        context["path"] = self.request.path
        context["target_id"] = self.target_id
        context["query"] = self.query
        context["filter_query"] = self.filter_query
        context["filters"] = build_filters_template_dict(self.filter)

        return context

hr_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from HTMXListViewDemo.views import HtmxListView
from hr_app.models import Person


# Create your views here.
class IndexView(TemplateView):
    template_name = "index.html"


class PersonListView(HtmxListView):
    paginate_by = 10
    model = Person
    template_name = "partials/_person_list.html"
    target_id = "#person-list"
    order_by = "name"
    queryset = Person.objects.all()

hr_app/templates/index.html
{% extends "base.html" %}

{% block content %}

	<div class="row">
		<div class="col mt-4">
			<h1>HTMXListView Demo</h1>
			<p>The table below uses HTMXListView and is sortable, filterable and has pagination using <a href="https://htmx.org/">HTMX</a> and
				<a href="https://django-cotton.com/">Django-Cotton.</a></p>
		</div>
	</div>

	<div class="row">
		<p><strong>Database Fields:</strong> name, date_of_birth, email, street_address, city, state</p>
		<p><strong>Model Property:</strong> age</p>
		<p>Depending on the datatype of a model property/calculated field the sorting can still work.</p>
		<div class="col mt-6" id="person-list" hx-get="{% url 'hr:person_list' %}" hx-trigger="load">

		</div>
	</div>

{% endblock %}

hr_app/templates/partials/_person_list.html
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<c-tables.header_cell name="name">Name</c-tables.header_cell>
				<c-tables.header_cell name="date_of_birth">D.O.B.</c-tables.header_cell>
				<c-tables.header_cell name="age">Age</c-tables.header_cell>
				<c-tables.header_cell name="email">Email</c-tables.header_cell>
				<c-tables.header_cell name="street_address">Street Address</c-tables.header_cell>
				<c-tables.header_cell name="city">City</c-tables.header_cell>
				<c-tables.header_cell name="state">State</c-tables.header_cell>
			</tr>
		</thead>
		<tbody>
		{% for item in object_list %}
			<tr>
				<td>{{ item.name }}</td>
				<td>{{ item.date_of_birth }}</td>
				<td>{{ item.age }}</td>
				<td>{{ item.email }}</td>
				<td>{{ item.street_address }}</td>
				<td>{{ item.city }}</td>
				<td>{{ item.state }}</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
<c-tables.pager />
</div>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.7/dist/htmx.min.js"></script>
</head>
<body>

<div class="container">
	{% block content %}{% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/cotton/icons/chevron_down.html
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
	 stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
	 class="icon icon-tabler icons-tabler-outline icon-tabler-chevron-down {{ add_class }}" {{ attrs }}>
	<path stroke="none" d="M0 0h24v24H0z" fill="none"/>
	<path d="M6 9l6 6l6 -6"/>
</svg>

templates/cotton/icons/chevron_left.html
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
	 stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
	 class="icon icon-tabler icons-tabler-outline icon-tabler-chevron-left {{ add_class }}" {{ attrs }}>
	<path stroke="none" d="M0 0h24v24H0z" fill="none"/>
	<path d="M15 6l-6 6l6 6"/>
</svg>

templates/cotton/icons/chevron_right.html
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
	 stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
	 class="icon icon-tabler icons-tabler-outline icon-tabler-chevron-right {{ add_class }}" {{ attrs }}>
	<path stroke="none" d="M0 0h24v24H0z" fill="none"/>
	<path d="M9 6l6 6l-6 6"/>
</svg>

templates/cotton/icons/chevron_up.html
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
	 stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
	 class="icon icon-tabler icons-tabler-outline icon-tabler-chevron-up {{ add_class }}" {{ attrs }}>
	<path stroke="none" d="M0 0h24v24H0z" fill="none"/>
	<path d="M6 15l6 -6l6 6"/>
</svg>

templates/cotton/tables/head.html
<thead>
	<tr>
		{{ slot }}
	</tr>
</thead>

templates/cotton/tables/header_cell.html
<th class="cursor-pointer {{ add_class }}" hx-get="{{ path }}{% if page_obj %}?page={{ page_obj.number }}&{% else %}?{% endif %}{% if filter_query %}{{ filter_query }}&{% endif %}order_by={% if name == order_by %}-{{ name }}{% else %}{{ name }}{% endif %}"
	hx-target="{{ target_id }}">
	<div class="d-flex">
		<div class="flex-grow-1 align-bottom mt-1">
			{{ slot }}
		</div>
		{% if order_by %}
			{% if name == order_by %}
				<c-icons.chevron_up add_class="ms-1"/>
			{% elif "-"|add:name == order_by %}
				<c-icons.chevron_down add_class="ms-1"/>
			{% endif %}
		{% endif %}
	</div>
</th>

templates/cotton/tables/pager.html
<div class="row g-2 justify-content-center justify-content-sm-between">
	<div class="col-auto d-flex align-items-center">
		<p class="m-0 text-secondary">Showing <strong>{{ page_obj.start_index }} to {{ page_obj.end_index }}</strong> of
			<strong>{{ page_obj.paginator.count }} entries</strong></p>
	</div>
	<div class="col-auto">
		<ul class="pagination m-0 ms-auto" hx-target="{{ target_id }}">
			<li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
				<button type="button" class="page-link"
						{% if page_obj.has_previous %}hx-get="{{ request.path }}?page={{ page_obj.previous_page_number }}&{{ query }}"{% endif %}
						tabindex="-1" aria-disabled="true">
					<c-icons.chevron_left/>
				</button>
			</li>
			{% for page in page_range %}
				<li class="page-item {% if page_obj.number == page %}active{% endif %}">
					{% if page == page_obj.paginator.ELLIPSIS %}
						<span class="page-link">{{ page }}</span>
					{% else %}
						<button type="button" class="page-link {% if page_obj.number == page %}active{% endif %}"
								hx-get="{{ request.path }}?page={{ page }}&{{ query }}">{{ page }}</button>
					{% endif %}
				</li>
			{% endfor %}
			<li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
				<button type="button" class="page-link"
						{% if page_obj.has_next %}hx-get="{{ request.path }}?page={{ page_obj.next_page_number }}&{{ query }}"{% endif %}
						tabindex="-1" aria-disabled="true">
					<c-icons.chevron_right/>
				</button>
			</li>
		</ul>
	</div>
</div>